on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
          required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  shellcheck_job:
    runs-on: ubuntu-latest
    name: Runs Shellcheck
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Shellcheck Runner
        id: shellcheck
        uses: vkoski-godaddy/action-shellcheck@master
